all:
	gcc -Ofast magics.c -o ../../bin/magics
	#x86_64-w64-mingw32-gcc -Ofast magics.c -o ../../bin/magics.exe

debug:
	gcc magics.c -o ../../bin/magics
	#x86_64-w64-mingw32-gcc magics.c -o ../../bin/magics.exe

